source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecsMirror.git'


target 'XCUserGuideExample’ do
    platform :ios, '8.0'
    use_frameworks!
    pod 'AMPopTip'
end




